### PR TITLE
Fix overlap task title

### PR DESCRIPTION
**Pull request by MasterIceZ**
Fix overlap task name
(BEFORE)
image
(AFTER)
image

### CODE REVIEW

**Comment by pongsaphol** [comment]
@iammarkps

**Comment by pongsaphol** [comment]
```
13:33:08.794 | ./src/components/Task/Layout.tsx:22:30
13:33:08.794 | Type error: Type '{ task: Task; type: string; assessmentId: string \| undefined; }' is not assignable to type 'IntrinsicAttributes & { task: Task; assessmentId?: string \| undefined; }'.
13:33:08.794 | Property 'type' does not exist on type 'IntrinsicAttributes & { task: Task; assessmentId?: string \| undefined; }'.
13:33:08.794 |  
13:33:08.794 | 20 \|       <div className="align-center flex h-full w-screen justify-center px-4 pt-4">
13:33:08.794 | 21 \|         <div className="flex h-full w-full max-w-6xl flex-col gap-2 md:flex-row md:gap-8">
13:33:08.794 | > 22 \|           <Title task={task} type={type} assessmentId={assessmentId} />
13:33:08.794 | \|                              ^
13:33:08.794 | 23 \|         </div>
13:33:08.794 | 24 \|       </div>
13:33:08.795 | 25 \|       <div className="align-center flex h-full w-screen justify-center px-4 py-4">
13:33:08.827 | ELIFECYCLE  Command failed with exit code 1.
13:33:08.847 | Error: Command "pnpm run build" exited with 1
```
@MasterIceZ please fix the above error

**Comment by MasterIceZ** [comment]
It might be work right now.

But there is a problem with rendering pictures in solution tab.

**Comment by MasterIceZ** [comment]
I changed ``metaverse_1`` ro ``metaverse_2`` so it can be compile since picture compiling doesn't work right now.

**Comment by pongsaphol** [comment]
view #797

**Pull request closed without merging**
